########################################################################################################################
#
# ███████╗██╗░░██╗███████╗░█████╗░██████╗░
# ╚════██║██║░░██║██╔════╝██╔══██╗██╔══██╗
# ░░███╔═╝███████║█████╗░░███████║██║░░██║
# ██╔══╝░░██╔══██║██╔══╝░░██╔══██║██║░░██║
# ███████╗██║░░██║███████╗██║░░██║██████╔╝
# ╚══════╝╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═════╝░
#
# Commands:
# /zhead - zhead.use - Display commands
# /zhead reload - zhead.reload - Reload configurations files
# /zhead update - zhead.update - Force the download of heads
# /zhead version - - Display plugin version
# /zhead give <id> [<amount>] [<player>] - zhead.give - Give a head
#
########################################################################################################################

category:
  alphabet: Alphabet
  animals: Animals
  blocks: Blocks
  decoration: Decoration
  food_drinks: Food and Drinks
  humans: Humans
  humanoid: Humanoid
  miscellaneous: Miscellaneous
  monsters: Monsters
  plants: Plants

inventory:
  back: "&cBack to main menu"
  page: "&cPage %page%"
  heads:
    name: '&czHead &8%count% heads'
    item:
      name: "&c&l%category%"
      lore:
        - "&f%count% &7heads"
    refresh:
      name: "&c&lRefresh"
      lore:
        - "&8Click to refresh the heads database"
    informations:
      name: "&e&lInformations"
      lore:
        - ""
        - "&f%amount% &7heads"
        - "&7Updated at&8: &f%updated%"
        - ""
        - "&b/zhb &8<&7head&8> &8[<&7amount&8>] [<&7player&8>]"
        - ""
        - "&8Credit: &7minecraft-heads.com"
  pagination:
    name: "&c%category% &8%count% heads"
    item:
      name: "&f%name%"
      lore:
        - "&8%category%"
        - "&8%tags%"
        - "&fID&8: &7%id%"